nbcamp/til-app

TILApp.xcodeproj/project.pbxproj, TILApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json, TILApp/Utilities/CustomComponents.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogListTableViewCell.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift
- 블로그 목록 페이지 UI 구현
- 블로그 수정 페이지 UI 구현
- 뷰 전환 일단 present로 구현 -> 추후 push로 변경하기
<br /><br />
<p align="center">
</p>
<br /><br />
resolve #14
=> [Feat] 블로그 목록 UI 작성

TILApp/Views/MyProfileViewController/MyProfileViewController.swift
[FEATURE]: 내 정보 화면 UI 구현
flexlayout 라이브러리 사용시 버튼을 눌러도 반응이 없어서 pinlayout으로만 수정구현
---
resolve #9
=> [Feat] 내 정보 화면 UI 구현

TILApp/Views/MyProfileViewController/MyProfileViewController.swift
[Refactor] 내 정보 화면 코드 수정 및 이미지 변경
---
resolve #32
=> [Refactor] 내 정보 화면 코드 수정 및 이미지 변경

.swiftlint.yml, TILApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TILApp/Models/Blog.swift, TILApp/Models/Post.swift, TILApp/Models/User.swift, TILApp/Resources/SceneDelegate.swift, TILApp/Services/APIService.swift, TILApp/Views/Test/TestNetworkViewController.swift
사용자 로그인, 블로그 및 포스트 CRUD 추가했습니다.
---
resolve #38
=> [API] API 연결 및 라우터 정리

TILApp.xcodeproj/project.pbxproj, TILApp/Utilities/CustomComponents.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/MyProfileViewController/EditTagViewController.swift, TILApp/Views/MyProfileViewController/TagCollectionViewCell.swift, TILApp/Views/MyProfileViewController/TagCollectionViewFlowLayout.swift, TILApp/Views/MyProfileViewController/editTagViewController.swift
- TIL 게시물 수정 화면 UI 작성
- 태그 갯수 및 태그 길이 제한 관련 논의 필요
---
resolve #11
=> [Feat] TIL 게시물 수정 화면 UI 작성

TILApp/Resources/SceneDelegate.swift, TILApp/Utilities/CustomComponents.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogListTableViewCell.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/EditTagViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/TagCollectionViewCell.swift
- 블로그 정보 편집 화면 UI 작성
- 블로그 관리 페이지 연결
- 블로그 목록 관련 컴포넌트 variant 생성
---
resolve #15
=> [Feat] 블로그 정보 편집 화면 UI 작성

TILApp.xcodeproj/project.pbxproj, TILApp/Views/CommunityView/WebViewController.swift
[Feat/10] 웹뷰 페이지 UI 작업
---
resolve #10
=> [Feat] 웹뷰 페이지 UI 작업 #10

TILApp/Views/CommunityView/CommunityTableViewCell.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListTableViewCell.swift, TILApp/Views/Shared/Components/CustomCommunityTILView.swift, TILApp/Views/Shared/Components/CustomTILView.swift, TILApp/Views/Shared/Components/CustomUserView.swift
- 커뮤니티 화면 테이블뷰 컴포넌트 디자인 변경 (날짜, 좋아요 버튼)
- 좋아요 버튼보다 넓은 UIView로 터치 영역 생성
---
resolve #30
=> [Refactor] 커뮤니티 목록 디자인 개선 #30

TILApp.xcodeproj/project.pbxproj, TILApp/Models/Blog.swift, TILApp/Models/Post.swift, TILApp/Models/User.swift, TILApp/Resources/Exported.swift, TILApp/Services/APIService.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/ViewModels/BlogViewModel.swift, TILApp/ViewModels/PostViewModel.swift, TILApp/ViewModels/UserViewModel.swift
- UserViewModle, BlogViewModel, PostViewModel 작성
---
resolve #48
=> [Feat] Model 보완 및 ViewModel 작성 #48

TILApp/Models/AuthUser.swift, TILApp/Models/Blog.swift, TILApp/Models/Post.swift, TILApp/Services/APIService.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/ViewModels/BlogViewModel.swift, TILApp/ViewModels/PostViewModel.swift, TILApp/Views/Test/TestNetworkViewController.swift
- Model 잘못된 내용 수정
- ViewModel 오류 수정
---
resolve #54
=> [Fix] API 관련 오류 수정

TILApp.xcodeproj/project.pbxproj, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/UserTableViewCell.swift
[Feat] 다른 사용자 정보 화면 UI 구현
*파랑색 View는 달력을 띄울 예정입니다.
---
resolve #12
=> [Feat] 다른 사용자 정보 화면 UI 구현

TILApp.xcodeproj/project.pbxproj, TILApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TILApp/Views/CalendarView/CalendarViewController.swift
달력 화면에 보이게 함, rss로 가져온 블로그 여러 블로그 동시에 표출 및 키워드로 필터링 까지
---
resolve #3
=> [Feat] 달력 UI 구현 RSS 기능 추가 #3

TILApp/Models/Blog.swift, TILApp/Resources/SceneDelegate.swift, TILApp/ViewModels/BlogViewModel.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/EditTagViewController.swift, TILApp/Views/Shared/Components/CustomBlogView.swift, TILApp/Views/Shared/Components/CustomLargeButton.swift, TILApp/Views/Shared/Components/CustomTextFieldView.swift, TILApp/Views/Shared/Components/CustomTextFieldViewWithValidation.swift
- 블로그 등록 페이지 유효성 검사 추가 및 기능 연결
- 블로그 목록 페이지 연결
- 키워드 등록 및 수정 페이지 유효성 검사 추가 및 기능 연결
- 블로그 수정 페이지 유효성 검사 추가 및 기능 연결
- 블로그 삭제 기능 연결
- CustomTextField 관련 UI 및 기능 자잘한 수정
- 키워드, 태그 CRUD 뷰모델 작성 및 연결
- 대표 블로그 설정 관련 수정 필요 
- 유저 정보 및 블로그 API 불러오는 시점 조절 필요 (기능 연결 완료 후)
- TODO에 적어놓은 RSS 자동완성 함수 연결 필요
---
resolve #47
=> [Feat] 블로그 등록, 수정, 삭제 기능 연결 #47

TILApp.xcodeproj/project.pbxproj, TILApp/ViewModels/AuthViewModel.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/UserTableViewCell.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/MyProfileTableViewCell.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
[Feat] 데이터 연결 및 모델 수정
---
resolve #57
=> [Feat] 사용자 정보 수정 및 탈퇴 기능 연결 #57

TILApp/Models/User.swift, TILApp/ViewModels/UserViewModel.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListTableViewCell.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/CustomFollowButton.swift, TILApp/Views/Shared/Components/CustomUserView.swift
- 팔로우 관리 페이지 연결 및 기능 추가
- 테이블뷰 스크롤 위치 저장 기능
- 테이블뷰 리로드 관련 이슈 -> 팔로우 후 바로 언팔로우 안됨... 
---
resolve #59
=> [Feat] 팔로우 관리 페이지 연결 및 기능 추가 #59

TILApp.xcodeproj/project.pbxproj, TILApp/Resources/SceneDelegate.swift, TILApp/Utilities/Extensions/UIViewController+Ext.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/SeeMoreBottomSheetViewController.swift, TILApp/Views/Shared/LoadingViewController.swift
- feat: 앱 접근 시 사용자 정보 불러오도록 개선
- feat: Loading 화면 및 로그아웃 경고창 추가
---
resolve #53
=> [Feat] 인증 확인 및 로딩 화면 추가

TILApp/Models/User.swift, TILApp/ViewModels/UserViewModel.swift, TILApp/Views/CommunityView/FollowListTableViewCell.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/Shared/Components/CustomFollowButton.swift, TILApp/Views/Shared/Components/CustomUserView.swift
- 기본적인 변수명, 컬러명 변경
- CustomFollowButton: 네이밍 변경
- CustomUserView: 네이밍 변경
- FollowListViewController: 팔로우 버튼 관련 기능, segmentedControl title 동기화 관련 수정 및 리팩토링
- 스크롤 위치 저장 로직 추가 (수정 필요)
---
resolve #69
=> [Refactor] 팔로우 관리 화면 로직 및 UI 점검 #69

.swiftlint.yml, TILApp.xcodeproj/project.pbxproj, TILApp/Models/Common.swift, TILApp/Models/Community.swift, TILApp/Models/Post.swift, TILApp/Resources/Exported.swift, TILApp/Resources/SceneDelegate.swift, TILApp/Services/APIService.swift, TILApp/Utilities/converter.swift, TILApp/ViewModels/CommunityViewModel.swift, TILApp/ViewModels/PostViewModel.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/Test/TestLayoutViewController.swift, TILApp/Views/Test/TestNetworkViewController.swift
- RefreshControl을 활용해서 당겨서 새로고침 기능 추가
- 자연스러움을 위해 로딩이 완료된 후 0.5초 후 화면 원상 복구
---
resolve #16
resolve #20
resolve #22
=> [Feat] 커뮤니티 목록 검색, PullToRefresh, 무한 스크롤 기능 추가 #16 #20 #22

TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/UserTableViewCell.swift, TILApp/Views/CommunityView/WebViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/MyProfileTableViewCell.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
[Refactor] 코드 리뷰 대응 및 버그 수정
- UserProfileVC : 더미데이터 삭제, 뷰모델 데이터 연결 등
- MyProfileVC : 테이블뷰 버그 수정(register issue), 데이터 연결 등
- EditProfileVC : 데이터 연결
- WebVC : 함수 호출 변경 및 키보드 내리기 추가
resolve #67
=> [Refactor] 사용자 정보 화면 코드 리뷰 대응 및 버그 수정

TILApp.xcodeproj/project.pbxproj, TILApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TILApp/Models/AuthUser.swift, TILApp/Models/Blog.swift, TILApp/Models/Community.swift, TILApp/Models/Post.swift, TILApp/Models/User.swift, TILApp/Resources/SceneDelegate.swift, TILApp/Services/APIService.swift, TILApp/Utilities/converter.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/ViewModels/BlogViewModel.swift, TILApp/ViewModels/CommunityViewModel.swift, TILApp/ViewModels/PostViewModel.swift, TILApp/ViewModels/UserViewModel.swift, TILApp/Views/AuthView/SignInViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift, TILApp/Views/Shared/Components/CustomCommunityTILView.swift, TILApp/Views/Shared/Components/CustomFollowButton.swift, TILApp/Views/Shared/Components/HorizontalTagsCollectionView.swift, TILApp/Views/Test/TestNetworkViewController.swift
- API 전면 재작업
- MoyaSugar 라이브러리 적용 (편의성 증가)
- APIService에 따른 ViewModel 재작성
- ViewModel 수정에 따른 로직 및 UI 재작업
- 자잘한 UI 오류 수정
---
resolve #86
resolve #90
resolve #73
resolve #89
resolve #91
=> [Feat/API] APIService 재작성 및 ViewModel 전면 수정, UI 적용 #86

TILApp/Utilities/Extensions/UIViewController+Ext.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/EditTagViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
- 키보드 내리기 UIViewController extension으로 만들고 적용
---
resolve #97
=> [Feat] 전 화면 키보드 내리기 기능 추가 #97

TILApp/Views/AuthView/SignInViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/WebViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/SeeMoreBottomSheetViewController.swift
이용약관 및 개인정보 처리방 침 추가 및 WebViewController 화면 전환
PinLayout 오류 수정
SignInViewController -> pravicyLabel tabGesture추가 (이용 약관 페이지 이동)
SeeMoreBottomSheet -> 이용 약관 페이지 항목 추가 및 레이아웃 수정
---
resolve #82 
resolve #92
=> [Feature] 이용약관 및 개인정보처리방침 추가 및 WebViewController 화면 전환 #82 #92

TILApp/Views/Shared/LoadingViewController.swift
- 크기 1.5배 키움
- 색상 흰색으로 고정
---
resolve #107
=> [Feat] 로딩 화면 로딩 표시 위치 및 색상 조정 #107

TILApp.xcodeproj/project.pbxproj, TILApp/Utilities/Extensions/UITableView+Ext.swift, TILApp/Views/CalendarView/CalendarViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserViewController.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift
- 테이블뷰 separator extension으로 관리
- systemGray6 컬러
---
resolve #98
=> [Feat] 전 화면 테이블뷰 구분선 UI 변경 #98

TILApp.xcodeproj/project.pbxproj, TILApp/Models/Community.swift, TILApp/Models/Post.swift, TILApp/Services/APIService.swift, TILApp/Utilities/Extensions/UIViewController+Ext.swift, TILApp/ViewModels/PostViewModel.swift, TILApp/Views/CommunityView/CommunityTableViewCell.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileTableViewCell.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/CustomCommunityTILView.swift, TILApp/Views/Shared/Components/LikeButton.swift
- 내 정보 화면 및 사용자 화면 작성글 및 좋아요 목록 표시
- 커뮤니티 화면 좋아요 기능 연결
---
resolve #77
=> [Feat] 게시물 및 좋아요 목록 표시, 좋아요 기능 연결 #77

TILApp/Views/MyProfileViewController/ProfileEditViewController.swift, TILApp/Views/Shared/Components/CustomUserView.swift
- CommunityViewController, FollowListViewController 기본이미지 변경으로 인한
CustomUserView 수정
---
resolve #114
=> [Fix] 기본 프로필 이미지 변경 (회색 -> 아이콘) #114

TILApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/SeeMoreBottomSheetViewController.swift
- 내 정보 화면 사용자 이름 표시 안 되는 문제 수정
- PinLayout 대신 FlexLayout 사용하도록 개선
- 다른 사용자 화면 레이아웃 개선
- 더 보기 메뉴 화면 바깥에 눌렀을 때 닫히도록 개선
- 더 보기 메뉴에서 닫히는 애니메이션 중첩 안 되는 문제 수정
---
resolve #120
=> [Fix] 내 정보 및 다른 사용자 화면 레이아웃 오류 수정

TILApp/Resources/SceneDelegate.swift
다크모드 삭제(강제 라이트 모드)
---
resolve #119
=> [Feat] 다크모드 삭제(강제 라이트 모드) #119

TILApp/Models/User.swift, TILApp/ViewModels/BlogViewModel.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserViewController.swift
- 팔로우 리스트 마지막 작성일 로직 추가
---
resolve #76
=> [Feat/API] TIL 마지막 작성일 #76

TILApp/Views/CommunityView/CommunityViewController.swift
- searchBar.searchTextField.delegate를 적용하여 textFieldShouldClear 함수 작성 후 처리
---
resolve #127
=> [Fix] 검색어를 모두 지웠을 때 키보드가 내려가는 문제 수정 #127

TILApp/Views/CalendarView/CalendarViewController.swift
달력 스와이프 기능 추가 및 달력 재 선택시 선택 해제기능 추가
---
resolve #111
=> [Fix] 달력 스와이프 기능 추가 및 달력 재 선택시 선택 해제기능 #111

TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift
- 다른 사용자 더 보기 메뉴 버튼 두 번 눌러야 하는 문제 수정
- 다른 사용자 화면 하단 탭바 숨기기
---
resolve #124
=> [Fix] 다른 사용자 더 보기 메뉴 버튼 두 번 눌러야 하는 문제 수정 #124

TILApp/Views/MyProfileViewController/MyProfileViewController.swift
내 정보 화면 더보기 메뉴 중 WebViewController로 전환메뉴 애니메이션 변경
resolve #129
=> [Fix] 내 정보 화면 더보기 메뉴 WebViewController 전환 애니메이션 변경 #129

TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/CustomSegmentedControl.swift
- Segmented Control UI 커스텀
- 사용중인 부분 수정사항 적용
---
resolve #131
=> [Feat] Segmented Control UI 커스텀 #131

TILApp/Views/CommunityView/UserProfileViewController.swift
다른 유저의 대표블로그 URL 누른후 뒤로가기 누르면 앱이 꺼지는 문제
resolve #135
=> [Fix] 다른 유저의 대표블로그 URL 누른후 뒤로가기 누르면 앱이 꺼지는 문제 #135

TILApp.xcodeproj/project.pbxproj, TILApp/Models/AuthUser.swift, TILApp/Models/Post.swift, TILApp/Models/Rss.swift, TILApp/Models/User.swift, TILApp/Services/APIService.swift, TILApp/Services/RssService.swift, TILApp/Utilities/Extensions/Date+Ext.swift, TILApp/Utilities/converter.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/ViewModels/CommunityViewModel.swift, TILApp/ViewModels/RssViewModel.swift, TILApp/Views/AuthView/SignInViewController.swift, TILApp/Views/CalendarView/CalendarViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/WebViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlogEditViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift, TILApp/Views/Shared/RootViewController.swift
- RSS Model 이름 변경
- RssService 작성 (rss 문서 불러오기)
- RssViewModel 재작성 (데이터 구조 작업, API Post 요청 추가)
- CalendarViewController 재작업 및 자잘한 버그 수정
---
resolve #110
=> [Feat] TIL 게시글 서버 전송 기능 추가 및 전반적인 재작업 #110

TILApp.xcodeproj/project.pbxproj, TILApp/Utilities/WebViewWarmer.swift, TILApp/Views/CalendarView/CalendarViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/WebViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserViewController.swift, TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
- WebViewWarmer 추가로 WebView 로딩 시간 단축
- TabBar와 ToolBar 레이아웃 오류 수정
- WebView 로딩 화면 추가
```plaintext
적용 전:
1차    2차
2.10  1.81
2.28  1.50
1.77  1.56
1.66  1.56
1.36  1.46
1.63  1.52
1.77  1.64
적용 후:
1차   2차
1.28  1.19
1.17  1.15
1.17  1.25
1.19  1.17
1.17  1.09
1.10  1.13
1.26  1.27
```
1차 약 33.65% 향상, 2차 약 25.34% 향상
---
resolve #139
=> [Refactor] WebView 성능 개선 #139

TILApp/ViewModels/AuthViewModel.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
- 내 정보 수정 시 유효성 검사 추가
- 회원정보 수정 실패 시 로그인화면으로 돌아가는 문제 해결
---
resolve #151
=> [Feat] 내 정보 수정 시 유효성 검사 및 에러 핸들링 #151

TILApp/Models/AuthUser.swift, TILApp/Views/CalendarView/CalendarViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/Shared/RootViewController.swift
- 홈 화면 달력 화면 통합
- 새로운 블로그 추가 시 달력 화면으로 전환
---
resolve #150
=> [Feat] 홈 화면과 달력 화면 통합 #150

TILApp/Models/AuthUser.swift, TILApp/Models/User.swift, TILApp/Resources/SceneDelegate.swift
- 백그라운드에서 돌아왔을 때 홈 화면으로 돌아가는 문제 수정
---
resolve #146
=> [Feat] 백그라운드에서 돌아왔을 때 홈 화면으로 돌아가는 문제 수정 #146

TILApp/Models/User.swift, TILApp/Services/APIService.swift, TILApp/ViewModels/UserViewModel.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserTableViewCell.swift, TILApp/Views/MyProfileViewController/BlockedUserViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/CustomBlockedUserView.swift
- 사용자 차단 및 신고 기능 연결
- 차단한 사용자 목록 표시 및 차단 해제 기능 추가
- 빈 목록일 경우, 플레이스홀더 화면 추가
- 내 정보 화면, 사용자 화면에도 테이블에 플레이스홀더 추가
---
resolve #148
resolve #103
=> [Feat] 사용자 차단 및 신고 기능 추가 #148

TILApp/ViewModels/AuthViewModel.swift, TILApp/ViewModels/RssViewModel.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift
- 블로그 등록 시 RSS 불러오도록 개선
- 사용자 게시글 수 갱신 안 되는 문제 수정
---
resolve #145
=> [Feat] 블로그 등록 시 RSS 불러오도록 개선 #145

TILApp/Views/MyProfileViewController/BlogListViewController.swift, TILApp/Views/Shared/Components/AvatarImageView.swift
- fix: 사용자 정보 수정 화면에서 프로필 이미지가 보이지 않는 문제 수정
- fix: 블로그 목록 플레이스 홀더 화면 추가
---
resolve #157
=> [Fix] 사용자 정보 수정 화면에서 프로필 이미지가 보이지 않는 문제 수정 #157

TILApp/Views/Shared/Components/LikeButton.swift
- 좋아요 아이콘이 깜빡거리는 문제 해결
---
resolve #156
=> [Fix] 좋아요 아이콘 깜빡 거리는 문제 수정 #156

TILApp/Views/Shared/Components/CustomKeywordView.swift, TILApp/Views/Shared/Components/CustomTagHeaderView.swift
=> [Feat] 블로그 게시물 자동 태그 설정 화면 플레이스홀더 작성 #160

TILApp.xcodeproj/project.pbxproj, TILApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TILApp/Models/Community.swift, TILApp/Services/APIService.swift, TILApp/Utilities/Extensions/UIImageView+Ext.swift, TILApp/Utilities/converter.swift, TILApp/ViewModels/CommunityViewModel.swift, TILApp/Views/CommunityView/CommunityTableViewCell.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListTableViewCell.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/BlockedUserTableViewCell.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/AvatarImageView.swift, TILApp/Views/Shared/Components/CustomBlockedUserView.swift, TILApp/Views/Shared/Components/CustomCommunityTILView.swift, TILApp/Views/Shared/Components/CustomUserView.swift, TILApp/Views/Shared/Components/LikeButton.swift
- fix: 요청 시 Bool 값이 아닌 문자열로 전달되는 문제 수정 (블로그 업데이트 안 되는 문제 수정)
- fix: 커뮤니티 및 좋아요 화면 목록 순서 변경되는 문제 수정
- fix: 좋아요 버튼 깜빡이는 문제 수정
- fix: 레이아웃 깨지는 문제 수정 (kingfisher 제거)
- fix: sort 쿼리 변경
- fix: 좋아요 목록에 반영 안 되는 문제 수정
---
resolve #161
resolve #168
resolve #169
=> [Fix] 버그 수정 #161

TILApp/ViewModels/CommunityViewModel.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift
- fix: 팔로워수, 좋아요 표시 동기화 문제 해결
---
resolve #171
=> [Fix] 좋아요 해제 시 커뮤니티에 반영 안되는 문제 #171

TILApp/Views/CalendarView/CalendarViewController.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/CommunityView/FollowListViewController.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/CommunityView/WebViewController.swift, TILApp/Views/HomeView/HomeViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/AvatarImageView.swift
- fix: WebView 외부 링크로 이동 가능하도록 개선
- fix: 빈 프로필 화면 테두리 안 보이는 문제 수정
- feat: 내 정보 화면에서 WebView 이동 로직 추가
- feat: 팔로워, 팔로잉 다른 사용자 화면 연결
- feat: 다른 사용자 차단 시 커뮤니티 화면에서 제거하도록 개선
- feat: 내 정보, 다른 사용자, 팔로우 화면 새로고침 추가
---
resolve #177
resolve #178
resolve #179
resolve #180
resolve #181
resolve #183
=> [Fix] WebView 외부 링크로 이동 가능하도록 개선 외 자잘한 오류 수정 및 개선 #177

TILApp/ViewModels/PostViewModel.swift, TILApp/Views/CommunityView/UserProfileViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift
- 다른 사용자 화면에 WebView를 추가했습니다.
- WebView에서 좋아요 기능을 사용할 수 있도록 개선했습니다.
- 좋아요 관련 오류를 수정했습니다. (서버)
---
resolve #184
=> [Fix] 내 정보 및 다른 사용자 화면 게시글 WebView 및 좋아요 기능 추가 #184

TILApp/Utilities/converter.swift, TILApp/Views/MyProfileViewController/BlogRegisterViewController.swift, TILApp/Views/Shared/Components/CustomTextFieldView.swift
1. 블로그 이름 유효성 검사 수정
2. 블로그 url입력 시 형식에 맞게끔 수정되어 적용
3. 블로그 url 입력 시 rss 주소는 자동으로 입력되는 기능 적용
4. rss 주소 수정시 url에 있는 블로그명과 같은지 유효성 검사
5. rss 주소 수정시 rss 주소 형식인지 유효성 검사
6. textfield 영타 첫자 대문자 고정 해제
UI 변경을 포함한 작업이라면 여기에 스크린샷을 남겨주세요.
resolve #147 
resolve #167
=> [Feat] 블로그 등록시 URL유효성 기능 추가 #147 #167

TILApp/Views/CommunityView/CommunityTableViewCell.swift, TILApp/Views/CommunityView/CommunityViewController.swift, TILApp/Views/MyProfileViewController/MyProfileViewController.swift, TILApp/Views/Shared/Components/CustomCommunityTILView.swift
커뮤니티 페이지 차단 / 신고 기능 추가
내 정보 좋아요 목록 차단 / 신고 기능 추가
---
resolve #193
=> [Feat] 커뮤니티 페이지 차단 / 신고 기능 추가 #193

TILApp/Resources/SceneDelegate.swift, TILApp/Views/AuthView/AgreeTermsViewController.swift
- 이용 약관 탭 시 색상 변경되는 문제 방지
- 로그인 화면 및 약관 동의 화면 로직 개선
UI 변경을 포함한 작업이라면 여기에 스크린샷을 남겨주세요.
---
resolve #198
=> [Fix] 이용 약관 동의 버튼 색상 변경 방지 및 네비게이션 로직 개선 #198

TILApp/Views/CalendarView/CalendarViewController.swift
- 달력 작성일 표시 안 되는 문제 수정
---
resolve #195
=> [Fix] 달력 작성일 표시 안 되는 문제 수정 #196

TILApp/Views/Shared/RootViewController.swift
- 각 TabBar 화면마다 하나의 Navigation로 감싸서 문제 해결
---
resolve #200
=> [Fix] 탭바가 붕 뜨는 문제 수정 #200

TILApp/Views/CommunityView/WebViewController.swift
- WebView가 메모리에서 해제가 되지 않는 문제가 있어 수정했습니다.
---
resolve #203
=> [Fix] WebView 메모리 해제가 안 되는 문제 수정 #203

TILApp/Resources/SceneDelegate.swift, TILApp/ViewModels/AuthViewModel.swift, TILApp/Views/AuthView/SignInViewController.swift
- 약관 동의 화면으로 넘어가지 않는 문제를 수정했습니다.
---
resolve #205
=> [Fix] 약관 동의 화면으로 넘어가지 않는 문제 수정 #205
